// <auto-generated />
namespace SocialApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Socialapp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Socialapp));
        
        string IMigrationMetadata.Id
        {
            get { return "202103141635204_Social-app"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
